title: "All Punk (Pixel Art) News, All The Time! - Fuck Yeah, It's Punk Week! - Punk Is Dead, Long Live Punk"

excerpt_separator: "<!-- more -->"


##  try using same format as in source (easier with cross-ref links?)
permalink: /:year-:month-:day-:title.html

exclude:
- README.md
- LICENSE.md


plugins:
- jekyll-relative-links
- jekyll-feed
- jekyll-avatar
- jemoji


###
## see https://github.com/benbalter/jekyll-relative-links
##   check why not working?
##   requires permalink pretty or such?
##   try with permalink w/o  .html - why? why not?

relative_links:
  enabled:  true

