title: "All Punk (Pixel Art) News, All The Time! - Fuck Yeah, It's Punk Week! - Punk Is Dead, Long Live Punk"

excerpt_separator: "<!-- more -->"


##  try using same format as in source (easier with cross-ref links?)
permalink: /:year-:month-:day-:title.html
## permalink: /:year-:month-:day-:title


exclude:
- README.md
- LICENSE.md


plugins:
- jekyll-feed
- jekyll-avatar
- jemoji
## - jekyll-relative-links


###
## see https://github.com/benbalter/jekyll-relative-links
##   check why not working?
##   requires permalink pretty or such?
##   try with permalink w/o  .html - why? why not?
##  note: looks like it works in posts BUT not in pages!!!
#
# relative_links:
#  enabled:     true
#  collections: true
